---
- src: {{cookiecutter.required_role_name}}
  version: {{cookiecutter.required_role_version}}
- src: entercloudsuite.prometheus-exporter
  version: 1.0.4
- src: entercloudsuite.consul
  version: 1.0.1
